
# Appveyor configuration file

# Suggested by https://github.com/kf6kjg in https://github.com/luca-piccioni/OpenGL.Net/issues/44; great idea
init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME" } else { $env:TAG_VERSION = "v0.5.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  global:
    SLN_BUILD_OPTS: /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    NUNIT_RUN: NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe
    NUNIT_OPTS: --noheader
    NUNIT_WHERE: --where="cat=GL || cat=EGL || cat =WGL || cat=GL_VERSION_1_0 || cat=Math || cat=Framework || cat=Toolkit_CoreUI"
    COVER_RUN: OpenCover.4.6.519\tools\OpenCover.Console.exe
    COVER_OPTS: -register:user -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -hideskipped:All
    COVER_EXLUDE: -excludebyfile:"*OpenGL.Net.Test*;*OpenGL.Net\DeviceContextGLX.cs;*OpenGL.Net\Glx.cs" -excludebyattribute:OpenGL.RequiredByFeatureAttribute
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SLN_PATH: OpenGL.Net_VC14.sln
      PUBLISH_NUGET: false
      HAS_NETCORE: false
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      SLN_PATH: OpenGL.Net_VC15.sln
      PUBLISH_NUGET: true
      HAS_NETCORE: true

pull_requests:
  do_not_increment_build_number: true

clone_folder: C:\OpenGL.Net

matrix:
  fast_finish: true

skip_commits:
  message: /Update README.md/

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore %SLN_PATH%

build_script:
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Release /p:Platform="Any CPU"
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Release /p:Platform="x86"
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Release /p:Platform="x64"
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Debug /p:Platform="Any CPU"
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Debug /p:Platform="x86"
  - cmd: msbuild %SLN_PATH% %SLN_BUILD_OPTS% /property:Configuration=Debug /p:Platform="x64"

# Happy to have a GL 1.1 software driver ^^
test: off

test_script:
  - nunit3-console OpenGL.Net.Test\bin\net461\Release\OpenGL.Net.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --result=TestOpenGL.Net_net461.xml;format=AppVeyor
  - nunit3-console OpenGL.Net.Test\bin\net35\Release\OpenGL.Net.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --result=TestOpenGL.Net_net35.xml;format=AppVeyor
  - nunit3-console OpenGL.Net.CoreUI.Test\bin\net461\Release\OpenGL.Net.CoreUI.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --result=TestOpenGL.Net.CoreUI_net461.xml;format=AppVeyor
  - nunit3-console OpenGL.Net.Test\bin\net461\Release\OpenGL.Net.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --x86 --result=TestOpenGL.Net_net461_x86.xml;format=AppVeyor
  - nunit3-console OpenGL.Net.Test\bin\net35\Release\OpenGL.Net.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --x86 --result=TestOpenGL.Net_net35_x86.xml;format=AppVeyor
  - nunit3-console OpenGL.Net.CoreUI.Test\bin\net461\Release\OpenGL.Net.CoreUI.Test.dll %NUNIT_WHERE% %NUNIT_OPTS% --x86 --result=TestOpenGL.Net.CoreUI_net461_x86.xml;format=AppVeyor

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net_net461.xml))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net_net35.xml))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net.CoreUI_net461.xml))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net_net461_x86.xml))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net_net35_x86.xml))
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestOpenGL.Net.CoreUI_net461_x86.xml))
  - pip install codecov
  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"OpenGL.Net.Test\bin\net461\Release\OpenGL.Net.Test.dll" -output:.\CovOpenGL.Net_net461.xml
  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"--x86 OpenGL.Net.Test\bin\net461\Release\OpenGL.Net.Test.dll" -output:.\CovOpenGL.Net_net461_x86.xml
#  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"OpenGL.Net.Test\bin\net35\Release\OpenGL.Net.Test.dll" -output:.\CovOpenGL.Net_net35.xml
#  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"--x86 OpenGL.Net.Test\bin\net35\Release\OpenGL.Net.Test.dll" -output:.\CovOpenGL.Net_net35_x86.xml
  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"OpenGL.Net.CoreUI.Test\bin\net461\Release\OpenGL.Net.CoreUI.Test.dll" -output:.\CovOpenGL.Net.CoreUI_net461.xml
  - packages\%COVER_RUN% %COVER_OPTS% %COVER_EXCLUDE% -targetargs:"--x86 OpenGL.Net.CoreUI.Test\bin\net461\Release\OpenGL.Net.CoreUI.Test.dll" -output:.\CovOpenGL.Net.CoreUI_net461_x86.xml
  - codecov -f "CovOpenGL.Net_net461.xml" -F net461_Win32
  - codecov -f "CovOpenGL.Net_net461_x86.xml" -F net461_Win32_x86
#  - codecov -f "CovOpenGL.Net_net35.xml" -F net35_Win32
#  - codecov -f "CovOpenGL.Net_net35_x86.xml" -F net35_Win32_x86
  - codecov -f "CovOpenGL.Net.CoreUI_net461.xml" -F CoreUI_net461_Win32
  - codecov -f "CovOpenGL.Net.CoreUI_net461_x86.xml" -F CoreUI_net461_Win32_x86
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.Math.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.WinForms.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.Xamarin.Android.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.VideoCore.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.CoreProfile.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.ES2Profile.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - IF "%PUBLISH_NUGET%"=="true" nuget pack OpenGL.Net.CoreUI.nuspec -Version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: SL+6WBe3MTUTSwbc6RplwQMK3ILPR2J4cHdImwFPymhNKKjPjoblM6W3PdEItXOs
    skip_symbols: true
    on:
      appveyor_repo_tag: true
      PUBLISH_NUGET: true

nuget:
  disable_publish_on_pr: true
