
# Appveyor configuration file

# Suggested by https://github.com/kf6kjg in https://github.com/luca-piccioni/OpenGL.Net/issues/44; great idea
init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME" } else { $env:TAG_VERSION = "v0.5.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      SLN_PATH: OpenGL.Net_VC14.sln
      PUBLISH_NUGET: true
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      SLN_PATH: OpenGL.Net_VC15.sln
      PUBLISH_NUGET: false

pull_requests:
  do_not_increment_build_number: true

clone_folder: c:\OpenGL.Net

matrix:
  fast_finish: true

skip_commits:
  message: /Update README.md/

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore %SLN_PATH%

build_script:
  msbuild %SLN_PATH% /property:Configuration=Release /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# Happy to have a GL 1.1 software driver ^^
test: 
  assemblies: OpenGL.Net.Test\bin\**\Release\OpenGL.Net.Test.dll
  categories:
    only:
      - GL_VERSION_1_0
      - Math
      - Framework_KhronosApi
      - Framework_KhronosVersion
      - Framework_RemovedByFeatureAttribute
      - Framework_RequiredByFeatureAttribute
      - Framework_DeviceContext

after_test:
  - pip install codecov
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/nologo /timeout=1000 /noshadow OpenGL.Net.Test\bin\net461\Release\OpenGL.Net.Test.dll" -excludebyfile:"*OpenGL.Net.Test*;*OpenGL.Net\DeviceContextGLX.cs;*OpenGL.Net\Glx.cs" -excludebyattribute:OpenGL.RequiredByFeatureAttribute -hideskipped:All -output:.\OpenGL.Net_net461.xml
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/nologo /timeout=1000 /noshadow OpenGL.Net.Test\bin\net35\Release\OpenGL.Net.Test.dll" -excludebyfile:"*OpenGL.Net.Test*;*OpenGL.Net\DeviceContextGLX.cs;*OpenGL.Net\Glx.cs" -excludebyattribute:OpenGL.RequiredByFeatureAttribute -hideskipped:All -output:.\OpenGL.Net_net35.xml
  - codecov -f "OpenGL.Net_net461.xml" -F net461
  - codecov -f "OpenGL.Net_net35.xml" -F net35
  - nuget pack OpenGL.Net.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.Math.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.WinForms.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.Xamarin.Android.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.VideoCore.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.CoreProfile.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget pack OpenGL.Net.ES2Profile.nuspec -Version %APPVEYOR_BUILD_VERSION%
#  - nuget pack OpenGL.Net.Debug.nuspec -Version %APPVEYOR_BUILD_VERSION% -Symbol

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: SL+6WBe3MTUTSwbc6RplwQMK3ILPR2J4cHdImwFPymhNKKjPjoblM6W3PdEItXOs
    skip_symbols: true
    on:
      appveyor_repo_tag: true
      PUBLISH_NUGET: true

nuget:
  disable_publish_on_pr: true
