language: csharp
solution: OpenGL.Net_Mono.sln
addons:
  apt:
     packages:
        - xserver-xorg-video-dummy
        - xpra
        - mesa-utils
install:
  - nuget
  - sudo nuget update -self
  - sudo nuget restore OpenGL.Net_Mono.sln
#  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release OpenGL.Net_Mono.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./OpenGL.Net.Test/bin/Release/OpenGL.Net.Test.dll
