language: csharp
solution: OpenGL.Net_Mono.sln
addons:
  apt:
     packages:
        - xserver-xorg-video-dummy
        - xpra
        - mesa-utils
install:
  - sudo nuget update -self
  - sudo nuget restore OpenGL.Net_Mono.sln
  - sudo nuget restore OpenGL.Net_VC14.sln
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 6 # give xvfb some time to start
script:
  - mono --version
  - xbuild /p:Configuration=Release OpenGL.Net_Mono.sln
  - glxinfo
  - mono ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe --where="cat=Framework || cat=Math" ./OpenGL.Net.Test/bin/net461/Release/OpenGL.Net.Test.dll
  - mono ./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -register:user -target:"packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe" -targetargs:"OpenGL.Net.Test/bin/net461/Release/OpenGL.Net.Test.dll" -excludebyfile:"*OpenGL.Net*.Test*" -excludebyattribute:OpenGL.RequiredByFeatureAttribute -hideskipped:All -output:./OpenGL.Net_net461.xml
  - mono ./packages/Codecov.1.0.3/codecov.exe -f "OpenGL.Net_net461.xml" -F net461_Linux
